name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    needs: test-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            cd ~/PiTempLogger
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            pkill -f main.py || true
            nohup python3 src/main.py &
