name: CD

on:
  push:
    branches: [ main ]

jobs:
  # 1) Install deps, run lint and tests
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint with flake8
        run: |
          source venv/bin/activate
          flake8 src/

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest --maxfail=1 --disable-warnings -q

  # 2) Deploy over SSH if lint/tests pass
  deploy:
    needs: test-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install requirements (for any local pre-deploy scripts)
        run: pip install -r requirements.txt

      - name: Deploy to Pi via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          # optional: if your key has a passphrase, include:
          # passphrase: ${{ secrets.PI_SSH_PASSPHRASE }}
          script: |
            cd ~/PiTempLogger
            git pull origin main
            source venv/bin/activate || python3 -m venv venv && source venv/bin/activate
            pip install -r requirements.txt
            pkill -f main.py || true
            nohup python3 src/main.py &>/dev/null &
