name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage pytest pytest-cov pylint

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD/src" >> $GITHUB_ENV

      - name: Lint with pylint
        run: pylint src --exit-zero

      - name: Run tests with coverage
        # `|| true` makes sure even if pytest errors (exit code 1/2), this step still exits 0
        run: pytest --cov=src --cov-report=xml || true

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
